# .github/workflows/e2e.yml
name: E2E Tests

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Set up environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" >> .env
      - name: Set up test database
        run: |
          npx prisma generate
          npx prisma migrate deploy
      - name: Build app
        run: npm run build
      - name: Start app
        run: npm run start &
      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to start... attempt $i"
            sleep 2
          done
      - name: Run Cypress E2E tests
        run: npm run cypress:run:ci
